image: node:10.15

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - build
  - deploy
  
lint:
  stage: test
  script:
  - npm run lint

unit-testing:
  stage: test
  script:
  - npm test

build-test:
  stage: test
  script:
  - npm run build

syncGitlab:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
  - curl -X GET http://$JENKINS_ADDRESS/job/codi-08-consultaMensajesCobroComprador/buildWithParameters?token=$JENKINS_TOKEN
