apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: gib-pasaportes
    deploymentconfig: gib-pasaportes
  name: gib-pasaportes
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    app: gib-pasaportes
    deploymentconfig: gib-pasaportes
  template:
    metadata:
      labels:
        app: gib-pasaportes
        deploymentconfig: gib-pasaportes
      name: gib-pasaportes
    spec:
      containers:
      - env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        envFrom:
        - configMapRef:
            name: conexion-postgres
        image: nexus-0.dev.openshift.multivaloresgf.local:18444/codi/gib-pasaportes:qa
        imagePullPolicy: IfNotPresent
        name: gib-pasaportes
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /describe
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /opt/app-root/routes
          name: rutas
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultmode: 420
          name: rutas
        name: rutas
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - gib-pasaportes
      from:
        kind: ImageStreamTag
        name: gib-pasaportes:qa
        namespace: codi-qa
